### ISSUE TITLE
How is it compiled?

### ISSUE THREAD

**Issue by diablobash** [yourmnbbn/tiny-csgo-client#10]
How exactly is it compiled? I downloaded Visual Studio 2022 and installed C++. I downloaded the dependencies from the links you provided. I extracted the downloaded files to where the build.bat is and edited the build.bat file as 

```
set HL2SDK_DIR="hl2sdk"
set ASIO_DIR="asio"

if %HL2SDK_DIR%==""  (
    echo Warning: Please set hl2sdk-csgo path in build.bat before running.
    eit \b
)

if %ASIO_DIR%==""  (
    echo Warning: Please set asio path in build.bat before running.
    exit \b
)

cmake -G "Visual Studio 16 2019" -A Win32 -B "vs2019" -DHL2SDK-CSGO:PATH=%HL2SDK_DIR% -DASIO-SRC:PATH=%ASIO_DIR%
cmake --build vs2019 --config Release

```
. After double clicking Build.bat and running it, nothing happens. I wonder if there is such a thing as a video on compilation?

**Comment by yourmnbbn** [comment]
For vs2022 the value of the -G option should be `visual studio 17 2022` instead of the current one, I suppose.

**Comment by diablobash** [comment]
I managed to compile. The exe file was created and I moved the files in bin/windows with it. When I double click on the exe, the console screen opens and closes for 1 second. How will I run it?

**Comment by diablobash** [comment]
I am running the exe with the command `"tiny-csgo-client.exe -ip 46.174.50.174 -port 27025 -name diablobash"`. But it gives the error in the image.
![image](https://user-images.githubusercontent.com/112769923/188314655-86a89c28-8488-4a52-b69c-4a29b30c4541.png)

**Comment by diablobash** [comment]
When typing -ticket, it gives two different errors.

![image](https://user-images.githubusercontent.com/112769923/188316347-38140699-e293-47a2-afef-8ecbe84d6dcd.png)

![image](https://user-images.githubusercontent.com/112769923/188316621-be17d6e1-f55b-4917-8433-738b8614d002.png)

**Comment by yourmnbbn** [comment]
Well, for your latest replies which has been deleted for I guess the sensitive information, are you using official steam or modified version? Is your steam working as expected? Normally the steam api won't has initialization failure.

And with -ticket option you have to give a valid ticket generated by ticketgen in tools.

**Comment by diablobash** [comment]
yes
