### ISSUE TITLE
Tiny-csgo-client-limited

### ISSUE THREAD

**Issue by HexMr** [yourmnbbn/tiny-csgo-client#14]
Hello, will you implement the option of connecting to tiny-csgo-server in a limited version of the client? I tried to do it myself but ran into problems I didn't understand. In what time would you implement this feature? I really care about implementing this dependency quickly. 
I am waiting for your answer.

**Comment by yourmnbbn** [comment]
Limited version of the client will not be updated until #12 being completed. The most important reason is GC communication. So far some progress has been made but still far from complete. Once it's done, current main branch will be deprecated and replaced by the limited version with all the existing functionality.

**Comment by yourmnbbn** [comment]
I think limited version is used to authenticate players. If not or you have other usage of it please reopen the issue and describe your request. And tiny-csgo-client-limited will be deprecated and tiny-steam-client will do the job in the future. 
https://github.com/yourmnbbn/csgo-fake-server
