### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HexMr** [yourmnbbn/tiny-csgo-client#15]
Hello, I have a few questions for you, they are related to tinyclient and tinyserver, but they are not a bug, rather an issue of some kind, my idea, but I need some answers to be able to implement it. I wrote an email to you in which I explained exactly what I mean. I hope you will write me back.
I am waiting for your answer.

**Comment by HexMr** [comment]
Thank you for the reply to the email, I have sent you a reply. Could you look at this email more often?

**Comment by yourmnbbn** [comment]
This is not related to the project itself.
