### ISSUE TITLE
Exits on CSVCMsg_CmdKeyValues_t

### ISSUE THREAD

**Issue by tv1993** [yourmnbbn/tiny-csgo-client#17]
Hi, I've build the client successfully and it also starts and connects to GC and I get the reservation id

Output start:
Trying to establish connection with GC, this may take a while...
GC Connection established for client
...
Trying to request server reservation id from GC, this may take a while...
Get server reservation id 0xBC7244302612E242
Output end:

Looks like the account connected to the server or requested the information but then the process exits.
Output start:
Counter-Strike: Global Offensive
Map: de_map
Players: 1 (0 bots) / 64 humans
Build: 8802
Server Number: 4

Receive NetMessage CSVCMsg_CmdKeyValues_t, print as string:
Output end:

I tried to implement a few debug messages in functions to understand where it stops.

Output start:
DEBUG ProcessPacket(length);
DEBUG int flags = ProcessPacketHeader(msg);
DEBUG ProcessPacket, !ProcessMessages
DEBUG Are we at the end?
Output end:

This loop gets printed 36 times and then the process exits after receiving NetMessage CSVCMsg_CmdKeyValues_t.

Currently im not using ticketgen to generate a ticket, I use the full client with running steam, bound with start argunment on same client port as the tiny client. Any idea why this is happening and how I can fix this?

**Comment by yourmnbbn** [comment]
Through the limited information you've provided I currently can't figure out what kind of crash is it. It is now working fine in my test environment. You can try the following approaches to debug yourself.

```
1. Debug using visual studio. (CMake will generate vs project files when compiling the project)
2. Try to connect to a pure server without any plugins to see if it would happen again.
3. Try to connect to some other public servers to see if there would be a successful connection.
```

**Comment by tv1993** [comment]
Im so sorry, compiling issue :/
