### ISSUE TITLE
Fun fact

### ISSUE THREAD

**Issue by HexMr** [yourmnbbn/tiny-csgo-client#20]
Hello, I noticed that someone on a popular scam forum has created a thread related to your programs, maybe we can learn something interesting from this? Can you talk about the topic? After all, no one knows these programs better than you.
https://www.unknowncheats.me/forum/counterstrike-global-offensive/567689-customer-authorization.html
Can you comment on this thread?

**Comment by yourmnbbn** [comment]
I guess he is just another one who wants to make a fake server with fake players count, and if so, steam-user node library can achieve what he want.

**Comment by HexMr** [comment]
But you don't know what is happening on the valve server side, you only know how the authorization works, and he probably wants to skip the ticket issues and authorize directly on the steam server, is it feasible?

**Comment by tv1993** [comment]
He changed the link in his thread, so probably not interested in tiny-client anymore 😆

**Comment by HexMr** [comment]
Maybe I don't want to popularize it?

**Comment by yourmnbbn** [comment]
Maybe my guessing was right and he saw my comment. 
>But you don't know what is happening on the valve server side, you only know how the authorization works, and he probably wants to skip the ticket issues and authorize directly on the steam server, is it feasible?

No, you will never know what is happening on the back-end server. GC communication was also like the one between client and server. They also use protobuf to do the message exchange but encrypted with higher security algorithm. The public key was discovered and published by the steam-node library. 

So everything we have to do which depends on the steam api like login account, generating ticket, register dedicated server and authenticating ticket etc. Under the hood is sending and receiving protobuf messages between us and the CM server. Getting CM server list is a public steam web api. Protobuf definition is provided by the steam-node library either. Thus, we now get everything we need. network connection(tcp or web socket), target CM server, protobuf definition and encryption key. We can emulate steam client and login thousands of accounts at one time in one environment. That's also what that library can do, pretending to be a steam client instance. Similarly tiny client is also pretending to be a normal client by simply creating network connection, sending and receiving messages.

Digging into the source code of the steam-user library will help all those who wants to implement a fake server. I hope this explanation would help.

**Comment by Scui1** [comment]
### Fun fact
You created the thread and you're pretending it's not you.
HexMr = Hievn
