### ISSUE TITLE
Issue with building project

### ISSUE THREAD

**Issue by Ragnoji** [yourmnbbn/tiny-csgo-client#8]
Could you know the problem i am facing when trying to build project? Could it be related to usage of vs2022?
Logs:
```D:\tiny-csgo-client>build.bat

D:\tiny-csgo-client>set HL2SDK_DIR="D:\tiny-csgo-client\dependencies\hl2sdk"

D:\tiny-csgo-client>set ASIO_DIR="D:\tiny-csgo-client\dependencies\asio\asio"

D:\tiny-csgo-client>if "D:\tiny-csgo-client\dependencies\hl2sdk" == "" (
echo Warning: Please set hl2sdk-csgo path in build.bat before running.
 exit /b
)

D:\tiny-csgo-client>if "D:\tiny-csgo-client\dependencies\asio\asio" == "" (
echo Warning: Please set asio path in build.bat before running.
 exit /b
)

D:\tiny-csgo-client>cmake -G "Visual Studio 17 2022" -A Win32 -B "vs2022" -DHL2SDK-CSGO:PATH="D:\tiny-csgo-client\dependencies\hl2sdk" -DASIO-SRC:PATH="D:\tiny-csgo-client\dependencies\asio\asio"
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/tiny-csgo-client/vs2022

D:\tiny-csgo-client>cmake --build vs2022 --config Release
MSBuild version 17.3.0+f67e3d35e for .NET Framework
  cl-main.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\yvals_core.h(1410,1): warning
 C4005: '__cpp_lib_ranges': macro redefinition [D:\tiny-csgo-client\vs2022\tiny-csgo-client-limited.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\yvals_core.h(1410,1): message
 : '__cpp_lib_ranges' previously declared on the command line [D:\tiny-csgo-client\vs2022\tiny-csgo-client-limited.vcxp
roj]
D:\tiny-csgo-client\include\netmessage/netmessages.h(10,10): fatal  error C1083: Cannot open include file: 'inetmessage
.h': No such file or directory [D:\tiny-csgo-client\vs2022\tiny-csgo-client-limited.vcxproj]```

**Comment by yourmnbbn** [comment]
`inetmessage.h` is in hl2sdk-csgo. So it's probably because of the wrong path you've configured for that sdk.

**Comment by Ragnoji** [comment]
![image](https://user-images.githubusercontent.com/58487417/184623220-4fc4b19c-ac01-44c6-8855-6503040ef489.png)
![image](https://user-images.githubusercontent.com/58487417/184623236-25094eed-895e-4d54-b78b-d44f2c8d0809.png)
idk, looks correct for me, probably i don't see something

**Comment by Ragnoji** [comment]
including more directories helped to find these problematic files, for some reason CMake doesn't go deeper than included directory.
    ${HL2SDK-CSGO}/public
    ${HL2SDK-CSGO}/public/engine/protobuf

**Comment by yourmnbbn** [comment]
Ah, I might have mistakenly deleted the include directories of that branch while having used cached project configuration to test the compilation. Note that although limited version so far can run multiple client instances, it would have authentication issue. Clients might be kicked from server for steam authentication failure.

**Comment by Ragnoji** [comment]
> Ah, I might have mistakenly deleted the include directories of that branch while having used cached project configuration to test the compilation. Note that although limited version so far can run multiple client instances, it would have authentication issue. Clients might be kicked from server for steam authentication failure.

So far i can't even manage to connect at all. What should i do to connect? I'm generating ticket, using that ticket without cancelling client on this cmd process and starting tiny-csgo-client-limited.exe with this ticket and other data. Do i need to specify nickname according to accounts name or something?

**Comment by yourmnbbn** [comment]
Have you been kicked for no user logon? The behavior of the ticket is really weird in the limited version so far and it's still in progress.  And if you bypass this validation on the server that client is still not gonna be counted in the server browser. So if you want to manipulate the player count in the browser just use the normal version.

**Comment by Ragnoji** [comment]
> Have you been kicked for no user logon? The behavior of the ticket is really weird in the limited version so far and it's still in progress. And if you bypass this validation on the server that client is still not gonna be counted in the server browser. So if you want to manipulate the player count in the browser just use the normal version.

No, there is basically no connection logs on my server console, even tho ticket seems to be generated as it should, because i see that i'm online ingame. Also, my main question, could this simulated connection be used for getting Case reward on server?

**Comment by yourmnbbn** [comment]
> Also, my main question, could this simulated connection be used for getting Case reward on server?

If this is your real purpose then you shouldn't use the limited version. I don't know if the dead players could be rewarded. This client so far won't be spawned in map because it doesn't even have the basic gui and control. When it finishes the connection process and being active in server, just like the normal client stays in the team choosing menu forever. You can have a try.

**Comment by yourmnbbn** [comment]
> > Also, my main question, could this simulated connection be used for getting Case reward on server?
> 
> If this is your real purpose then you shouldn't use the limited version. I don't know if the dead players could be rewarded. This client so far won't be spawned in map because it doesn't even have the basic gui and control. When it finishes the connection process and being active in server, just like the normal client stays in the team choosing menu forever. You can have a try.

But as far as I can tell, the case reward is actually assigned by the GC and then notify the server, in GC's perspective, the tiny client is identical to the other normal players. It can't tell the difference. So technically yes.

**Comment by Ragnoji** [comment]
> > > Also, my main question, could this simulated connection be used for getting Case reward on server?
> > 
> > 
> > If this is your real purpose then you shouldn't use the limited version. I don't know if the dead players could be rewarded. This client so far won't be spawned in map because it doesn't even have the basic gui and control. When it finishes the connection process and being active in server, just like the normal client stays in the team choosing menu forever. You can have a try.
> 
> But as far as I can tell, the case reward is actually assigned by the GC and then notify the server, in GC's perspective, the tiny client is identical to the other normal players. It can't tell the difference. So technically yes.

Yeah, there is definitely some some bypass to simulate hundreds of accounts gathering cases. I saw screenshots from one guy with legit looking logs. Not much info regarding author, cause i wasn't the first person to see these screens
![image](https://user-images.githubusercontent.com/58487417/184665626-8341c6c1-f2fa-41b2-9b09-38d94b2a670b.png)
![image](https://user-images.githubusercontent.com/58487417/184665646-166382f2-781c-446a-bea0-a7ebd2b83334.png)

Text on Russian says 
Validation of ticket completed
...
Validation of ticket completed
Authorisation sends hello (i guess just some message to see when all tickets are checked idk)

**Comment by yourmnbbn** [comment]
Well, this is a fake server. The item drop firstly is requested by the server to GC, GC assigned all the drops and notify the server. If you want to look into this, you'll need both this project and [tiny-csgo-server](https://github.com/yourmnbbn/tiny-csgo-server). The screenshot is the console of the fake server.
